### ISSUE TITLE
Release google-cloud-workflows 0.2.0. Missing workflows_client.location_path

### ISSUE THREAD

**Issue by grant** [googleapis/python-workflows#21]
#### Environment details

  - OS type and version: OSX
  - Python version: `python --version` python37
  - pip version: `pip --version`: pip 20.1.1
  - `google-cloud-workflows` version: `pip show google-cloud-workflows`: Version: 0.1.0

#### Steps to reproduce

1. Try to use the function `workflows_client.location_path(PROJECT, LOCATION)` but you'll see a `'WorkflowsClient' object has no attribute 'location_path'` error
  1. You can use the `workflows_client.workflow_path(PROJECT, LOCATION, WORKFLOW)` https://github.com/googleapis/python-workflows/blob/ccddf0607d6af58ccf52e33ee1ff735a8034559a/google/cloud/workflows_v1beta/services/workflows/client.py#L149
1. Observe there's a [`common_location_path`](https://github.com/googleapis/python-workflows/blob/ccddf0607d6af58ccf52e33ee1ff735a8034559a/google/cloud/workflows_v1beta/services/workflows/client.py#L211) on GitHub, but we can't use it in our program. Why?

It looks like this function is only on GitHub, but not available in the latest package on pypi – 0.1.0.

---

Can we cut a new version of this library?

We have a branch: https://github.com/googleapis/python-workflows/tree/release-v0.2.0 and looks like there's a PR: https://github.com/googleapis/python-workflows/pull/14

Do we just need to merge that PR?

CC: @busunkim96

**Comment by busunkim96** [comment]
0.2.0 is now released. https://pypi.org/project/google-cloud-workflows/

**Comment by grant** [comment]
Thanks.
